// Trip: Seville & Portugal 2026
// Family trip: parents + 3yo and 6yo kids
// April 3–12, 2026

window.registerTrip({
  id: 'seville-2026',
  name: 'Seville & Portugal',
  subtitle: 'Mértola · Aracena · Seville · Monte Gordo',
  coverColor: '#e07b54',
  startDate: '2026-04-03',
  endDate: '2026-04-12',
  kidsFriendly: true,

  accommodations: [
    {
      id: 'acc-lisbon',
      name: 'Home — Lisbon Airport',
      location: 'Lisbon, Portugal',
      lat: 38.7756,
      lng: -9.1354,
      days: [],
      notes: 'Lisbon Humberto Delgado Airport (LIS)',
      isHome: true
    },
    {
      id: 'acc-mertola',
      name: 'Accommodation Mértola',
      location: 'Mértola, Portugal',
      lat: 37.6375,
      lng: -7.6615,
      days: ['2026-04-03', '2026-04-04', '2026-04-05'],
      notes: 'City center'
    },
    {
      id: 'acc-seville',
      name: 'Accommodation Seville',
      location: 'Seville, Spain',
      lat: 37.3935,
      lng: -5.9890,
      days: ['2026-04-06', '2026-04-07', '2026-04-08', '2026-04-09'],
      notes: 'Near Palacio de las Dueñas'
    },
    {
      id: 'acc-monte-gordo',
      name: 'Accommodation Monte Gordo',
      location: 'Monte Gordo, Portugal',
      lat: 37.1770,
      lng: -7.4551,
      days: ['2026-04-10', '2026-04-11', '2026-04-12'],
      notes: 'Beach area'
    }
  ],

  days: [
    {
      date: '2026-04-03',
      label: 'Lisbon → Mértola',
      destination: 'Mértola',
      emoji: '🇵🇹',
      country: 'Portugal',
      driving: {
        from: 'Lisbon',
        to: 'Mértola',
        approxKm: 280,
        approxMin: 180,
        note: 'Drive south from Lisbon along the A2/IP2'
      }
    },
    {
      date: '2026-04-04',
      label: 'Mértola',
      destination: 'Mértola',
      emoji: '🏰',
      country: 'Portugal',
      driving: null
    },
    {
      date: '2026-04-05',
      label: 'Mértola',
      destination: 'Mértola',
      emoji: '⛏️',
      country: 'Portugal',
      driving: null
    },
    {
      date: '2026-04-06',
      label: 'Aracena → Seville',
      destination: 'Aracena + Seville',
      emoji: '🦇',
      country: 'Spain',
      driving: {
        from: 'Mértola',
        to: 'Aracena',
        approxKm: 80,
        approxMin: 75,
        note: 'Morning drive Mértola → Aracena, then afternoon to Seville'
      }
    },
    {
      date: '2026-04-07',
      label: 'Seville',
      destination: 'Seville',
      emoji: '🏛️',
      country: 'Spain',
      driving: null
    },
    {
      date: '2026-04-08',
      label: 'Seville',
      destination: 'Seville',
      emoji: '🌉',
      country: 'Spain',
      driving: null
    },
    {
      date: '2026-04-09',
      label: 'Seville',
      destination: 'Seville',
      emoji: '⛪',
      country: 'Spain',
      driving: null
    },
    {
      date: '2026-04-10',
      label: 'Seville → Monte Gordo',
      destination: 'Monte Gordo',
      emoji: '🌊',
      country: 'Portugal',
      driving: {
        from: 'Seville',
        to: 'Monte Gordo',
        approxKm: 180,
        approxMin: 120,
        note: 'Afternoon drive to Monte Gordo beach'
      }
    },
    {
      date: '2026-04-11',
      label: 'Monte Gordo',
      destination: 'Monte Gordo',
      emoji: '🏖️',
      country: 'Portugal',
      driving: null
    },
    {
      date: '2026-04-12',
      label: 'Monte Gordo → Lisbon',
      destination: 'Lisbon',
      emoji: '🏠',
      country: 'Portugal',
      driving: {
        from: 'Monte Gordo',
        to: 'Lisbon',
        approxKm: 270,
        approxMin: 165,
        note: 'Return drive home via A22/A2'
      }
    }
  ],

  pois: [
    // ══════════════════════════════════════
    // MÉRTOLA
    // ══════════════════════════════════════
    {
      id: 'castelo-mertola',
      name: 'Castelo de Mértola',
      category: 'monument',
      destination: 'Mértola',
      lat: 37.6382,
      lng: -7.6612,
      rating: 4.6,
      ratingCount: 1240,
      cost: 0,
      costLabel: 'Free',
      duration: 1,
      description: 'Medieval castle perched above the confluence of the Guadiana and Oeiras rivers. The keep offers panoramic views over the white town and river. Originally a Roman fortification, later rebuilt by the Moors and then the Portuguese. Great for kids to explore the ramparts.',
      kidsRating: 5,
      energyCost: 2,
      source: 'user',
      confirmedBooking: false,
      bookAhead: false,
      gmapsUrl: 'https://maps.google.com/?q=Castelo+de+Mertola',
      wikipediaTitle: 'Mértola_Castle',
      tags: ['castle', 'views', 'history'],
      openingHours: 'Tue–Sun 9:00–12:30, 14:00–17:30',
      availableDays: ['2026-04-03', '2026-04-04', '2026-04-05']
    },
    {
      id: 'igreja-matriz',
      name: 'Igreja Matriz de Mértola',
      category: 'monument',
      destination: 'Mértola',
      lat: 37.6371,
      lng: -7.6616,
      rating: 4.7,
      ratingCount: 890,
      cost: 0,
      costLabel: 'Free',
      duration: 0.5,
      description: 'A unique church that was converted from a mosque — one of the best-preserved examples of this transformation in Portugal. The horseshoe arches and mihrab are still visible inside. A fascinating piece of history for the family.',
      kidsRating: 4,
      energyCost: 1,
      source: 'user',
      confirmedBooking: false,
      bookAhead: false,
      gmapsUrl: 'https://maps.google.com/?q=Igreja+Matriz+Mertola',
      wikipediaTitle: 'Mértola',
      tags: ['church', 'moorish', 'history'],
      openingHours: 'Daily 9:00–12:00, 14:00–18:00',
      availableDays: ['2026-04-03', '2026-04-04', '2026-04-05']
    },
    {
      id: 'museu-arte-islamica',
      name: 'Museu Arte Islâmica',
      category: 'museum',
      destination: 'Mértola',
      lat: 37.6373,
      lng: -7.6614,
      rating: 4.5,
      ratingCount: 560,
      cost: 2,
      costLabel: '€',
      duration: 1,
      description: 'One of the most important Islamic art museums in Portugal, housing artifacts from Mértola\'s Muslim period (9th–13th centuries). Features ceramics, jewelry, coins, and architectural fragments. Well-curated with good child-friendly displays.',
      kidsRating: 3,
      energyCost: 1,
      source: 'user',
      confirmedBooking: false,
      bookAhead: false,
      gmapsUrl: 'https://maps.google.com/?q=Museu+Arte+Islamica+Mertola',
      wikipediaTitle: 'Mértola',
      tags: ['islamic art', 'history', 'museum'],
      openingHours: 'Tue–Sun 9:00–12:30, 14:00–17:30',
      availableDays: ['2026-04-03', '2026-04-04', '2026-04-05']
    },
    {
      id: 'alcacova-islamica',
      name: 'Alcáçova Islâmica',
      category: 'monument',
      destination: 'Mértola',
      lat: 37.6378,
      lng: -7.6609,
      rating: 4.3,
      ratingCount: 320,
      cost: 0,
      costLabel: 'Free',
      duration: 0.5,
      description: 'Archaeological site revealing the Islamic citadel of Mértola. Excavated remains show the urban layout of the medieval Moorish town, including house foundations, streets, and water systems. An open-air window into the past.',
      kidsRating: 4,
      energyCost: 1,
      source: 'suggested',
      confirmedBooking: false,
      bookAhead: false,
      gmapsUrl: 'https://maps.google.com/?q=Alcacova+Islamica+Mertola',
      wikipediaTitle: 'Mértola',
      tags: ['archaeology', 'islamic', 'history'],
      openingHours: 'Always open',
      availableDays: ['2026-04-03', '2026-04-04', '2026-04-05']
    },
    {
      id: 'torre-do-rio',
      name: 'Torre do Rio',
      category: 'monument',
      destination: 'Mértola',
      lat: 37.6355,
      lng: -7.6621,
      rating: 4.2,
      ratingCount: 210,
      cost: 0,
      costLabel: 'Free',
      duration: 0.5,
      description: 'A medieval watchtower on the banks of the Guadiana river. A short walk from the town center, this tower was used to control river traffic. The riverside path here is beautiful, especially at sunset, and great for a stroll with kids.',
      kidsRating: 4,
      energyCost: 1,
      source: 'suggested',
      confirmedBooking: false,
      bookAhead: false,
      gmapsUrl: 'https://maps.google.com/?q=Torre+do+Rio+Mertola',
      wikipediaTitle: 'Mértola',
      tags: ['tower', 'river', 'medieval'],
      openingHours: 'Always open',
      availableDays: ['2026-04-03', '2026-04-04', '2026-04-05']
    },
    {
      id: 'mina-sao-domingos',
      name: 'Mina de São Domingos',
      category: 'nature',
      destination: 'Mértola',
      lat: 37.6469,
      lng: -7.5025,
      rating: 4.6,
      ratingCount: 780,
      cost: 0,
      costLabel: 'Free',
      duration: 2,
      description: 'A dramatic abandoned copper mine 20km east of Mértola. The landscape is surreal — rusted machinery, colorful mineral-stained pools, and ochre cliffs. The mine operated from Roman times until 1966. The nearby lagoon (lagoa) has striking orange-red water from iron minerals. A unique and memorable excursion.',
      kidsRating: 4,
      energyCost: 2,
      source: 'suggested',
      confirmedBooking: false,
      bookAhead: false,
      gmapsUrl: 'https://maps.google.com/?q=Mina+de+Sao+Domingos',
      wikipediaTitle: 'São_Domingos_Mine',
      tags: ['mine', 'nature', 'industrial history', 'excursion'],
      openingHours: 'Always open (outdoor site)',
      availableDays: ['2026-04-03', '2026-04-04', '2026-04-05'],
      notes: '20km excursion from Mértola — drive or bike'
    },
    {
      id: 'restaurante-alengarve',
      name: 'Restaurante Alengarve',
      category: 'food',
      destination: 'Mértola',
      lat: 37.6368,
      lng: -7.6618,
      rating: 4.4,
      ratingCount: 430,
      cost: 25,
      costLabel: '€€',
      duration: 1.5,
      description: 'A well-regarded local restaurant in Mértola serving traditional Alentejo and Algarve cuisine. Known for slow-roasted meats, fresh river fish, and local cheeses. Family-friendly atmosphere with a good kids menu.',
      kidsRating: 4,
      energyCost: 1,
      source: 'suggested',
      confirmedBooking: false,
      bookAhead: false,
      gmapsUrl: 'https://maps.google.com/?q=Restaurante+Alengarve+Mertola',
      wikipediaTitle: 'Mértola',
      tags: ['restaurant', 'portuguese', 'local'],
      openingHours: 'Daily 12:00–15:00, 19:00–22:00',
      availableDays: ['2026-04-03', '2026-04-04', '2026-04-05']
    },

    // ══════════════════════════════════════
    // ARACENA
    // ══════════════════════════════════════
    {
      id: 'gruta-maravillas',
      name: 'Gruta de las Maravillas',
      category: 'cave',
      destination: 'Aracena',
      lat: 37.8862,
      lng: -6.5534,
      rating: 4.7,
      ratingCount: 3200,
      cost: 13,
      costLabel: '€€',
      duration: 1,
      description: 'One of Spain\'s most spectacular caves, featuring vast chambers adorned with stalactites, stalagmites, and colorful mineral formations. The guided tour covers 1.2km through 12 interconnected chambers. Absolutely magical for children — like entering another world. The temperature inside is a constant 16°C.',
      kidsRating: 5,
      energyCost: 1,
      source: 'user',
      confirmedBooking: false,
      bookAhead: true,
      gmapsUrl: 'https://maps.google.com/?q=Gruta+de+las+Maravillas',
      wikipediaTitle: 'Gruta_de_las_Maravillas',
      tags: ['cave', 'stalactites', 'guided tour'],
      openingHours: 'Daily 10:00–18:00 (last tour 17:15)',
      availableDays: ['2026-04-06'],
      notes: '⚠️ Book tickets in advance — sells out quickly!'
    },
    {
      id: 'castillo-aracena',
      name: 'Castillo de Aracena',
      category: 'monument',
      destination: 'Aracena',
      lat: 37.8875,
      lng: -6.5536,
      rating: 4.4,
      ratingCount: 1100,
      cost: 2,
      costLabel: '€',
      duration: 0.75,
      description: 'A hilltop castle built by the Knights Templar in the 13th century, with stunning views over the Sierra de Aracena. The site includes a Mudéjar church (Iglesia del Castillo) with a distinctive tower. A short but rewarding climb with great panoramic views.',
      kidsRating: 4,
      energyCost: 2,
      source: 'user',
      confirmedBooking: false,
      bookAhead: false,
      gmapsUrl: 'https://maps.google.com/?q=Castillo+de+Aracena',
      wikipediaTitle: 'Aracena',
      tags: ['castle', 'views', 'medieval'],
      openingHours: 'Daily 10:00–14:00, 16:00–19:00',
      availableDays: ['2026-04-06']
    },
    {
      id: 'museo-jamon',
      name: 'Museo del Jamón',
      category: 'food',
      destination: 'Aracena',
      lat: 37.8850,
      lng: -6.5520,
      rating: 4.3,
      ratingCount: 680,
      cost: 15,
      costLabel: '€€',
      duration: 0.75,
      description: 'A museum dedicated to the famous Jamón Ibérico from the Sierra de Aracena. Learn about the Iberian pig, the acorn (bellota) diet, and the curing process. Includes a tasting of high-quality hams and local products. A delicious and educational stop.',
      kidsRating: 3,
      energyCost: 1,
      source: 'suggested',
      confirmedBooking: false,
      bookAhead: false,
      gmapsUrl: 'https://maps.google.com/?q=Museo+del+Jamon+Aracena',
      wikipediaTitle: 'Jamón_ibérico',
      tags: ['food', 'jamón', 'museum', 'tasting'],
      openingHours: 'Daily 10:00–14:00, 17:00–20:00',
      availableDays: ['2026-04-06']
    },

    // ══════════════════════════════════════
    // SEVILLE
    // ══════════════════════════════════════
    {
      id: 'real-alcazar',
      name: 'Real Alcázar',
      category: 'monument',
      destination: 'Seville',
      lat: 37.3842,
      lng: -5.9909,
      rating: 4.8,
      ratingCount: 52000,
      cost: 14.50,
      costLabel: '€€',
      duration: 2.5,
      description: 'A UNESCO World Heritage royal palace, one of the most stunning examples of Mudéjar architecture in the world. Intricate tilework, carved plasterwork, and beautiful gardens make this a highlight of any Seville visit. Still used by the Spanish royal family. Kids love the maze-like gardens.',
      kidsRating: 5,
      energyCost: 2,
      source: 'user',
      confirmedBooking: false,
      bookAhead: true,
      gmapsUrl: 'https://maps.google.com/?q=Real+Alcazar+Seville',
      wikipediaTitle: 'Alcázar_of_Seville',
      tags: ['UNESCO', 'palace', 'gardens', 'moorish'],
      openingHours: 'Daily 9:30–19:00 (Apr–Sep), 9:30–17:00 (Oct–Mar)',
      availableDays: ['2026-04-06', '2026-04-07', '2026-04-08', '2026-04-09'],
      notes: 'UNESCO World Heritage — book tickets in advance!'
    },
    {
      id: 'catedral-giralda',
      name: 'Catedral + Giralda',
      category: 'monument',
      destination: 'Seville',
      lat: 37.3861,
      lng: -5.9928,
      rating: 4.7,
      ratingCount: 48000,
      cost: 11,
      costLabel: '€€',
      duration: 2,
      description: 'The world\'s largest Gothic cathedral, housing the tomb of Christopher Columbus. The iconic Giralda tower (originally a minaret) can be climbed via a series of ramps rather than stairs — meaning even young children can walk up! The views from the top are spectacular.',
      kidsRating: 4,
      energyCost: 2,
      source: 'user',
      confirmedBooking: false,
      bookAhead: false,
      gmapsUrl: 'https://maps.google.com/?q=Catedral+de+Sevilla',
      wikipediaTitle: 'Seville_Cathedral',
      tags: ['cathedral', 'Gothic', 'tower', 'Columbus'],
      openingHours: 'Mon 11:00–15:30, Tue–Sat 11:00–17:00, Sun 14:30–18:00',
      availableDays: ['2026-04-06', '2026-04-07', '2026-04-08', '2026-04-09'],
      notes: 'Giralda climb via ramp — no stairs, kids can do it!'
    },
    {
      id: 'barrio-santa-cruz',
      name: 'Barrio de Santa Cruz',
      category: 'neighborhood',
      destination: 'Seville',
      lat: 37.3856,
      lng: -5.9880,
      rating: 4.6,
      ratingCount: 28000,
      cost: 0,
      costLabel: 'Free',
      duration: 1.5,
      description: 'Seville\'s charming old Jewish quarter, a labyrinth of narrow whitewashed lanes, orange-tree-filled plazas, and flower-draped balconies. Perfect for wandering without a fixed route. Every corner reveals another beautiful courtyard or fountain. A magical place for families.',
      kidsRating: 5,
      energyCost: 2,
      source: 'user',
      confirmedBooking: false,
      bookAhead: false,
      gmapsUrl: 'https://maps.google.com/?q=Barrio+Santa+Cruz+Seville',
      wikipediaTitle: 'Barrio_Santa_Cruz,_Seville',
      tags: ['neighbourhood', 'historic', 'walking', 'photography'],
      openingHours: 'Always open',
      availableDays: ['2026-04-06', '2026-04-07', '2026-04-08', '2026-04-09']
    },
    {
      id: 'plaza-espana',
      name: 'Plaza de España',
      category: 'monument',
      destination: 'Seville',
      lat: 37.3773,
      lng: -5.9870,
      rating: 4.8,
      ratingCount: 65000,
      cost: 0,
      costLabel: 'Free',
      duration: 1.5,
      description: 'An extraordinary semi-circular plaza built for the 1929 Ibero-American Exposition. The elaborate tiled alcoves representing each Spanish province are stunning. Rent a rowboat on the canal that curves around the plaza (€4/person) — kids absolutely love it. One of Seville\'s most iconic sights.',
      kidsRating: 5,
      energyCost: 2,
      source: 'user',
      confirmedBooking: false,
      bookAhead: false,
      gmapsUrl: 'https://maps.google.com/?q=Plaza+de+Espana+Seville',
      wikipediaTitle: 'Plaza_de_España,_Seville',
      tags: ['plaza', 'architecture', 'boats', 'photography'],
      openingHours: 'Always open (boat hire 10:00–21:00)',
      availableDays: ['2026-04-06', '2026-04-07', '2026-04-08', '2026-04-09'],
      notes: 'Boat rental €4/person — kids LOVE it!'
    },
    {
      id: 'parque-maria-luisa',
      name: 'Parque de María Luisa',
      category: 'park',
      destination: 'Seville',
      lat: 37.3763,
      lng: -5.9875,
      rating: 4.7,
      ratingCount: 22000,
      cost: 0,
      costLabel: 'Free',
      duration: 1,
      description: 'Seville\'s main public park, adjacent to the Plaza de España. Shaded paths, fountains, peacocks roaming freely, and duck ponds make this a perfect rest stop for families. A cool green oasis in the city, ideal for kids who need to run around after a long day of sightseeing.',
      kidsRating: 5,
      energyCost: 1,
      source: 'user',
      confirmedBooking: false,
      bookAhead: false,
      gmapsUrl: 'https://maps.google.com/?q=Parque+Maria+Luisa+Seville',
      wikipediaTitle: 'Parque_de_María_Luisa',
      tags: ['park', 'nature', 'kids', 'relaxing'],
      openingHours: 'Daily 8:00–22:00',
      availableDays: ['2026-04-06', '2026-04-07', '2026-04-08', '2026-04-09']
    },
    {
      id: 'metropol-parasol',
      name: 'Metropol Parasol',
      category: 'monument',
      destination: 'Seville',
      lat: 37.3928,
      lng: -5.9922,
      rating: 4.4,
      ratingCount: 18000,
      cost: 3,
      costLabel: '€',
      duration: 1,
      description: 'The world\'s largest wooden structure, nicknamed "Las Setas" (The Mushrooms) by locals. Walk the elevated walkway for panoramic views of the city. Best visited at sunset when the city turns golden. Below, there\'s a Roman archaeological museum and a lively food market.',
      kidsRating: 4,
      energyCost: 1,
      source: 'user',
      confirmedBooking: false,
      bookAhead: false,
      gmapsUrl: 'https://maps.google.com/?q=Metropol+Parasol+Seville',
      wikipediaTitle: 'Metropol_Parasol',
      tags: ['modern architecture', 'views', 'sunset'],
      openingHours: 'Mon–Thu 9:30–23:00, Fri–Sun 9:30–23:30',
      availableDays: ['2026-04-06', '2026-04-07', '2026-04-08', '2026-04-09'],
      notes: 'Best at sunset for golden hour views!'
    },
    {
      id: 'triana',
      name: 'Barrio de Triana',
      category: 'neighborhood',
      destination: 'Seville',
      lat: 37.3831,
      lng: -6.0040,
      rating: 4.7,
      ratingCount: 31000,
      cost: 0,
      costLabel: 'Free',
      duration: 2,
      description: 'Seville\'s most characterful barrio, separated from the old city by the Guadalquivir river. The birthplace of flamenco, renowned for its ceramics, and home to a lively tapas scene. Cross the iconic Puente de Triana (Puente de Isabel II) and explore the riverside walk and colorful streets.',
      kidsRating: 4,
      energyCost: 2,
      source: 'user',
      confirmedBooking: false,
      bookAhead: false,
      gmapsUrl: 'https://maps.google.com/?q=Barrio+de+Triana+Seville',
      wikipediaTitle: 'Triana,_Seville',
      tags: ['neighbourhood', 'flamenco', 'ceramics', 'riverside'],
      openingHours: 'Always open',
      availableDays: ['2026-04-06', '2026-04-07', '2026-04-08', '2026-04-09']
    },
    {
      id: 'torre-del-oro',
      name: 'Torre del Oro',
      category: 'monument',
      destination: 'Seville',
      lat: 37.3825,
      lng: -5.9965,
      rating: 4.4,
      ratingCount: 14000,
      cost: 3,
      costLabel: '€',
      duration: 0.75,
      description: 'A 13th-century Moorish watchtower on the bank of the Guadalquivir. Originally one of two towers connected by a chain across the river to control access to Seville\'s port. Now a small naval museum. The golden tile exterior sparkles in the sun. A quick but satisfying stop.',
      kidsRating: 4,
      energyCost: 1,
      source: 'user',
      confirmedBooking: false,
      bookAhead: false,
      gmapsUrl: 'https://maps.google.com/?q=Torre+del+Oro+Seville',
      wikipediaTitle: 'Torre_del_Oro',
      tags: ['tower', 'moorish', 'museum', 'riverfront'],
      openingHours: 'Mon–Fri 9:30–18:45, Sat–Sun 10:30–18:45',
      availableDays: ['2026-04-06', '2026-04-07', '2026-04-08', '2026-04-09']
    },
    {
      id: 'palacio-duenas',
      name: 'Palacio de las Dueñas',
      category: 'monument',
      destination: 'Seville',
      lat: 37.3942,
      lng: -5.9895,
      rating: 4.6,
      ratingCount: 4800,
      cost: 12,
      costLabel: '€€',
      duration: 1.5,
      description: 'A stunning 15th-century palatial residence belonging to the House of Alba — one of Spain\'s most prominent noble families. The birthplace of the poet Antonio Machado. Beautiful Mudéjar courtyards, extensive art collection, and lovely gardens. Very close to the accommodation.',
      kidsRating: 3,
      energyCost: 1,
      source: 'user',
      confirmedBooking: false,
      bookAhead: false,
      gmapsUrl: 'https://maps.google.com/?q=Palacio+de+las+Duenas+Seville',
      wikipediaTitle: 'Palacio_de_las_Dueñas',
      tags: ['palace', 'art', 'gardens', 'noble'],
      openingHours: 'Daily 10:00–20:00 (Oct–Mar until 18:00)',
      availableDays: ['2026-04-06', '2026-04-07', '2026-04-08', '2026-04-09', '2026-04-10'],
      notes: 'Walking distance from accommodation'
    },
    {
      id: 'casa-pilatos',
      name: 'Casa de Pilatos',
      category: 'museum',
      destination: 'Seville',
      lat: 37.3883,
      lng: -5.9882,
      rating: 4.7,
      ratingCount: 7200,
      cost: 12,
      costLabel: '€€',
      duration: 1.5,
      description: 'An exquisite 16th-century palace blending Mudéjar, Gothic and Renaissance styles. Often less crowded than the Alcázar but arguably even more beautiful. The tiled courtyards and gardens are breathtaking. A hidden gem of Seville\'s architectural heritage.',
      kidsRating: 3,
      energyCost: 1,
      source: 'suggested',
      confirmedBooking: false,
      bookAhead: false,
      gmapsUrl: 'https://maps.google.com/?q=Casa+de+Pilatos+Seville',
      wikipediaTitle: 'Casa_de_Pilatos',
      tags: ['palace', 'Mudéjar', 'tiles', 'art'],
      openingHours: 'Daily 9:00–19:00 (Nov–Mar until 18:00)',
      availableDays: ['2026-04-06', '2026-04-07', '2026-04-08', '2026-04-09']
    },
    {
      id: 'isla-magica',
      name: 'Isla Mágica',
      category: 'entertainment',
      destination: 'Seville',
      lat: 37.4064,
      lng: -6.0026,
      rating: 4.1,
      ratingCount: 9800,
      cost: 26,
      costLabel: '€€€',
      duration: 5,
      description: 'A theme park on La Isla de la Cartuja themed around 16th-century Spanish explorers. Water rides, shows, rollercoasters (suitable for young kids), and pirate ships. A full-day adventure that kids will absolutely love. Reduced rates for children under 10.',
      kidsRating: 5,
      energyCost: 3,
      source: 'suggested',
      confirmedBooking: false,
      bookAhead: false,
      gmapsUrl: 'https://maps.google.com/?q=Isla+Magica+Seville',
      wikipediaTitle: 'Isla_Mágica',
      tags: ['theme park', 'kids', 'rides', 'water rides'],
      openingHours: 'Varies by season — check website',
      availableDays: ['2026-04-06', '2026-04-07', '2026-04-08', '2026-04-09'],
      notes: 'Full day activity — pack sunscreen and snacks!'
    },
    {
      id: 'el-arenal',
      name: 'Barrio del Arenal',
      category: 'neighborhood',
      destination: 'Seville',
      lat: 37.3840,
      lng: -5.9960,
      rating: 4.5,
      ratingCount: 8500,
      cost: 0,
      costLabel: 'Free',
      duration: 1,
      description: 'The historic waterfront district between the Cathedral and the Torre del Oro. Stroll along the Paseo Alcalde Marqués de Contadero riverfront promenade, watch the city from the water, and explore the bullring (Plaza de Toros de la Maestranza). A pleasant area for an evening walk.',
      kidsRating: 4,
      energyCost: 1,
      source: 'suggested',
      confirmedBooking: false,
      bookAhead: false,
      gmapsUrl: 'https://maps.google.com/?q=Barrio+del+Arenal+Seville',
      wikipediaTitle: 'El_Arenal,_Seville',
      tags: ['neighbourhood', 'riverfront', 'walking'],
      openingHours: 'Always open',
      availableDays: ['2026-04-06', '2026-04-07', '2026-04-08', '2026-04-09']
    },
    {
      id: 'museo-bellas-artes',
      name: 'Museo de Bellas Artes',
      category: 'museum',
      destination: 'Seville',
      lat: 37.3906,
      lng: -5.9985,
      rating: 4.5,
      ratingCount: 6200,
      cost: 0,
      costLabel: 'Free',
      duration: 1.5,
      description: 'One of Spain\'s finest fine art museums, housed in a beautiful 17th-century convent. The collection focuses on Seville\'s Golden Age painters, including Murillo, Zurbarán, and Valdés Leal. Free entry for EU citizens. The building itself — with its stunning baroque church — is worth seeing.',
      kidsRating: 2,
      energyCost: 1,
      source: 'suggested',
      confirmedBooking: false,
      bookAhead: false,
      gmapsUrl: 'https://maps.google.com/?q=Museo+Bellas+Artes+Seville',
      wikipediaTitle: 'Museum_of_Fine_Arts_of_Seville',
      tags: ['museum', 'art', 'painting', 'free'],
      openingHours: 'Tue–Sat 9:00–21:00, Sun 9:00–15:00',
      availableDays: ['2026-04-06', '2026-04-07', '2026-04-08', '2026-04-09']
    },
    {
      id: 'rinconillo',
      name: 'El Rinconcillo',
      category: 'bar',
      destination: 'Seville',
      lat: 37.3960,
      lng: -5.9968,
      rating: 4.4,
      ratingCount: 5600,
      cost: 30,
      costLabel: '€€',
      duration: 1.5,
      description: 'Seville\'s oldest bar, established in 1670 — still in operation over 350 years later! The classic Andalusian interior with tiled walls, dark wood, and hanging hams is unforgettable. Famous for its spinach with chickpeas (espinacas con garbanzos), fried fish, and excellent local wines. A piece of living history.',
      kidsRating: 3,
      energyCost: 1,
      source: 'user',
      confirmedBooking: true,
      bookAhead: true,
      gmapsUrl: 'https://maps.google.com/?q=El+Rinconcillo+Seville',
      wikipediaTitle: 'El_Rinconcillo',
      tags: ['historic bar', 'tapas', 'wine', 'traditional'],
      openingHours: 'Daily 13:00–02:00',
      availableDays: ['2026-04-06'],
      notes: '⭐ BOOKED for April 6 evening'
    },
    {
      id: 'espacio-eslava',
      name: 'Espacio Eslava',
      category: 'food',
      destination: 'Seville',
      lat: 37.3877,
      lng: -5.9959,
      rating: 4.7,
      ratingCount: 4200,
      cost: 40,
      costLabel: '€€€',
      duration: 2,
      description: 'A beloved Sevillian restaurant known for its innovative take on traditional Andalusian cuisine. Chef Ivan Vázquez has earned widespread acclaim for dishes like "Torrija de pan de autor con leche merengada" (egg-soaked bread with meringue). Consistently wins Seville\'s best tapas competitions. A genuine culinary highlight.',
      kidsRating: 3,
      energyCost: 1,
      source: 'user',
      confirmedBooking: true,
      bookAhead: true,
      gmapsUrl: 'https://maps.google.com/?q=Espacio+Eslava+Seville',
      wikipediaTitle: 'Seville',
      tags: ['restaurant', 'innovative', 'tapas', 'award-winning'],
      openingHours: 'Tue–Sun 13:00–16:00, 20:30–23:30',
      availableDays: ['2026-04-08'],
      notes: '⭐ BOOKED for April 8 evening'
    },
    {
      id: 'mercado-triana',
      name: 'Mercado de Triana',
      category: 'food',
      destination: 'Seville',
      lat: 37.3829,
      lng: -6.0049,
      rating: 4.5,
      ratingCount: 7800,
      cost: 10,
      costLabel: '€',
      duration: 1,
      description: 'A vibrant covered market in the heart of Triana, built over the ruins of the old Inquisition castle. Fresh produce, local specialties, ceramics, and excellent tapas bars inside. A great place to pick up local cheeses, charcuterie, and olive oil. Kids enjoy the lively atmosphere.',
      kidsRating: 4,
      energyCost: 1,
      source: 'suggested',
      confirmedBooking: false,
      bookAhead: false,
      gmapsUrl: 'https://maps.google.com/?q=Mercado+de+Triana+Seville',
      wikipediaTitle: 'Triana,_Seville',
      tags: ['market', 'food', 'local', 'tapas'],
      openingHours: 'Mon–Sat 9:00–15:00',
      availableDays: ['2026-04-06', '2026-04-07', '2026-04-08', '2026-04-09']
    },

    // ══════════════════════════════════════
    // MONTE GORDO
    // ══════════════════════════════════════
    {
      id: 'monte-gordo-beach',
      name: 'Praia de Monte Gordo',
      category: 'beach',
      destination: 'Monte Gordo',
      lat: 37.1770,
      lng: -7.4551,
      rating: 4.5,
      ratingCount: 3400,
      cost: 0,
      costLabel: 'Free',
      duration: 3,
      description: 'A long sandy beach on the Algarve coast, backed by pine forests. Wide, family-friendly, and typically uncrowded in April. The water is still cool but the sand is perfect for play. Beach bars (chiringuitos) open in season. A wonderful, relaxing end to the trip for everyone.',
      kidsRating: 5,
      energyCost: 1,
      source: 'user',
      confirmedBooking: false,
      bookAhead: false,
      gmapsUrl: 'https://maps.google.com/?q=Praia+de+Monte+Gordo',
      wikipediaTitle: 'Monte_Gordo',
      tags: ['beach', 'sand', 'family', 'relaxing'],
      openingHours: 'Always open',
      availableDays: ['2026-04-10', '2026-04-11', '2026-04-12']
    },
    {
      id: 'castro-marim',
      name: 'Castelo de Castro Marim',
      category: 'monument',
      destination: 'Monte Gordo',
      lat: 37.2144,
      lng: -7.4449,
      rating: 4.5,
      ratingCount: 2100,
      cost: 2,
      costLabel: '€',
      duration: 1.5,
      description: 'A medieval castle with stunning views over the Rio Guadiana and into Spain. The surrounding salt marshes are a natural reserve famous for flamingos (especially in spring!). A fun and educational stop with a castle that kids can freely explore. The flamingo viewing alone makes it worthwhile.',
      kidsRating: 4,
      energyCost: 2,
      source: 'suggested',
      confirmedBooking: false,
      bookAhead: false,
      gmapsUrl: 'https://maps.google.com/?q=Castelo+de+Castro+Marim',
      wikipediaTitle: 'Castro_Marim_Castle',
      tags: ['castle', 'flamingos', 'nature', 'views'],
      openingHours: 'Daily 9:00–17:00',
      availableDays: ['2026-04-10', '2026-04-11', '2026-04-12'],
      notes: '🦩 Flamingos in the salt marshes — best in spring!'
    },
    {
      id: 'tavira',
      name: 'Tavira',
      category: 'monument',
      destination: 'Monte Gordo',
      lat: 37.1262,
      lng: -7.6487,
      rating: 4.7,
      ratingCount: 5600,
      cost: 0,
      costLabel: 'Free',
      duration: 3,
      description: 'One of the most beautiful towns in the Algarve, about 30 minutes west of Monte Gordo. A Roman bridge, Moorish castle, traditional salt pans, and charming old town make for a perfect half-day excursion. The relaxed atmosphere and excellent seafood restaurants are a highlight.',
      kidsRating: 4,
      energyCost: 2,
      source: 'suggested',
      confirmedBooking: false,
      bookAhead: false,
      gmapsUrl: 'https://maps.google.com/?q=Tavira+Portugal',
      wikipediaTitle: 'Tavira',
      tags: ['town', 'algarve', 'roman bridge', 'seafood'],
      openingHours: 'Always open',
      availableDays: ['2026-04-10', '2026-04-11', '2026-04-12'],
      notes: '30 min drive from Monte Gordo'
    }
  ],

  defaultDayPlans: {
    '2026-04-03': ['castelo-mertola', 'igreja-matriz'],
    '2026-04-04': ['museu-arte-islamica', 'alcacova-islamica', 'torre-do-rio'],
    '2026-04-05': ['mina-sao-domingos'],
    '2026-04-06': ['gruta-maravillas', 'castillo-aracena', 'rinconillo'],
    '2026-04-07': ['real-alcazar', 'barrio-santa-cruz', 'metropol-parasol'],
    '2026-04-08': ['plaza-espana', 'parque-maria-luisa', 'triana', 'espacio-eslava'],
    '2026-04-09': ['catedral-giralda', 'torre-del-oro', 'el-arenal'],
    '2026-04-10': ['palacio-duenas'],
    '2026-04-11': ['monte-gordo-beach', 'castro-marim'],
    '2026-04-12': []
  }
});
